accounts/urls.py
from django.conf.urls import url

from .views import SignUpView, LoginView, LogOutView, SuccessView, LoggedOutView


app_name = 'accounts'

urlpatterns = [
    url(r'register/$', SignUpView.as_view(), name='signup'),
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'logout/$', LogOutView.as_view(), name='logout'),
    url(r'registration_done/$', SuccessView.as_view(), name='registration_done'),
    url(r'logged_out/$', LoggedOutView.as_view(), name='logged_out'),
]

profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import UpdateProfileView, ProfileView, UpdateLoginView, CreateProfileView, PasswordView, SuccessView


app_name = 'profiles'

urlpatterns = [
    url(r'create_profile/$', login_required(CreateProfileView.as_view()), name='create_profile'),
    url(r'update/(?P<pk>\d+)/$', login_required(UpdateProfileView.as_view()), name='update'),
    url(r'profile_home/$', login_required(ProfileView.as_view()), name='profile_home'),
    url(r'password_change/(?P<pk>\d+)/$', login_required(PasswordView.as_view()), name='password_change'),
    url(r'login_details/(?P<pk>\d+)/$', login_required(UpdateLoginView.as_view()), name='login_details'),
    url(r'profile_update/$', login_required(SuccessView.as_view()), name='profile_update'),
]

schedule/urls.py
from django.conf.urls import url

from schedule import views


app_name = 'schedule'

urlpatterns = [
    url(r'', views.schedule, name='schedule'),

]

talks/urls.py
from rest_framework import routers

from talks.views import TalkViewsSets
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from talks import views


app_name = 'talks'
router = routers.DefaultRouter()
router.register(r'talks', TalkViewsSets)


urlpatterns = [
    url(r'^submit_talk', login_required(views.submit_talk), name='submit_talk'),
    # url(r'^talk_list', login_required(views.TalkList.as_view()), name='talk_list'),
    url(r'^edit_talk/(?P<pk>\d+)/$', login_required(views.TalkView.as_view()), name='edit_talk'),
    url(r'^submitted', login_required(views.SuccessView.as_view()), name='submitted'),
    url(r'^accepted_talks', views.AcceptedTalksView.as_view(), name='accepted_talks'),
    # url(r'^talk_details/(?P<pk>\d+)/$', views.TalkDetailView.as_view(), name='talk_details'),
    ]

urlpatterns += router.urls

website/urls.py
from django.conf.urls import url
from website import views


app_name = 'website'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'accommodation', views.accommodation, name='accommodation'),
    url(r'cofc', views.cofc, name='cofc'),
    url(r'manifesto', views.manifesto, name='manifesto'),
    url(r'venue', views.venue, name='venue'),
    url(r'contact', views.contact, name='contact'),
    url(r'subscribe', views.subscribe, name='subscribe'),
    url(r'success', views.success, name='success'),
    url(r'thanks', views.thanks, name='thanks'),
    url(r'registration', views.registration, name='registration'),
    url(r'sprints', views.sprints, name='sprints'),
    url(r'2017', views.pyconzim_2017, name='pyconzim_2017'),
]

website/models.py
from django.db import models
from django.utils import timezone


class Contact(models.Model):
    name = models.CharField("full name", max_length=120)
    company = models.CharField("company name", max_length=120)
    email = models.EmailField("email address", max_length=120)
    message = models.TextField()
    email_date = models.DateTimeField(default=timezone.now)

    class Meta:
        managed = True

    def __str__(self):
        return self.name


class Subscription(models.Model):
   email = models.EmailField("email address", max_length=120)
   date_sub = models.DateTimeField("date subscribed", default=timezone.now)
   is_active = models.BooleanField(default=True)

   class Meta:
       managed = True

   def __str__(self):
       return self.email

website/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field


from .models import Contact, Subscription


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = ('name', 'company', 'email', 'message',)

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-Crispy_ContactForm'
        self.helper.form_class = 'form-horizontal'
        # Moving field labels into placeholders
        layout = self.helper.layout = Layout()
        for field_name, field in self.fields.items():
            layout.append(Field(field_name, placeholder=field.label))
        self.helper.form_show_labels = False
        self.helper.add_input(Submit('send', 'Send Message'))

class SubscribeForm(forms.ModelForm):

    class Meta:
        model = Subscription
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super(SubscribeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'id-Crispy_SubscribeForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.add_input(Submit('send', 'Notify me'))
        # Moving field labels into placeholders
        layout = self.helper.layout = Layout()
        for field_name, field in self.fields.items():
            layout.append(Field(field_name, placeholder=field.label))
        self.helper.form_show_labels = False

website/views.py
from __future__ import absolute_import
from django.shortcuts import render, reverse
from django.core.mail import send_mail
from django.http import HttpRequest, HttpResponseRedirect
from django.contrib import messages


from datetime import datetime


from .forms import ContactForm, SubscribeForm
from .models import Contact, Subscription 
from sponsors.models import Sponsor


def home(request):
    """Renders the home page."""
    assert isinstance(request, HttpRequest)
    contact_form = ContactForm()
    subscribe_form = SubscribeForm()
    platinum = Sponsor.objects.filter(category="Platinum")
    gold = Sponsor.objects.filter(category="Gold")
    silver = Sponsor.objects.filter(category="Silver")
    bronze = Sponsor.objects.filter(category="Bronze")
    individuals = Sponsor.objects.filter(type="I")

    return render(
        request,
        'website/index.html',
        {
            'title': 'Home',
            'message': 'Home Page',
            'year': datetime.now().year,
            'contact_form': contact_form,
            'subscribe_form': subscribe_form,
            'platinum': platinum,
            'gold': gold,
            'silver': silver,
            'bronze': bronze,
            'individuals': individuals,
        }
    )


def contact(request):
    # check captcha
    if request.method == "POST":
        contact_form = ContactForm(request.POST)

        if contact_form.is_valid():
            # process the data in contact_form.cleaned_data as required
            obj = Contact()  # gets new object
            obj.name = contact_form.cleaned_data['name']
            obj.company = contact_form.cleaned_data['company']
            obj.email = contact_form.cleaned_data['email']
            obj.message = contact_form.cleaned_data['message']
            # finally save the object in db
            obj.save()

            # send email to pycon_zim@gmail.com
            subject = "Message on Contact Form "
            message = 'A message was submitted on the website\n\n'
            message += 'Name: ' + contact_form.cleaned_data['name'] + '\n'
            message += 'Email: ' + contact_form.cleaned_data['email'] + '\n'
            message += 'Company: ' + contact_form.cleaned_data['company'] + '\n'
            message += 'Message:\n ' + contact_form.cleaned_data['message'] + '\n'

            sender = 'zim.pycon@gmail.com'

            recipient_list = ['zim.pycon@gmail.com']
            send_mail(subject, message, sender, recipient_list)

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('website:thanks'))
        
    else:
        # if a GET (or any other method) we'll create a blank form
        contact_form = ContactForm()

        return HttpResponseRedirect(reverse('website:home'))


def subscribe(request):
    if request.method == "POST":
        subscribe_form = SubscribeForm(request.POST)

        if subscribe_form.is_valid():
            # process the data in subscribe_form.cleaned_data as required
            obj = Subscription()  # gets new object
            obj.email = subscribe_form.cleaned_data['email']
            # finally save the object in db
            obj.save()

            return HttpResponseRedirect(reverse('website:success'))


"""Renders the success page"""
def success(request):
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'website/success.html',
        {
            'title': 'Success ',
            'message': 'Success',
            'year': datetime.now().year,
        }
    )


"""Renders the thanks page"""
def thanks(request):
    assert isinstance(request, HttpRequest)
    return render(
        request,
        'website/thanks.html',
        {
            'title': 'Message Sent ',
            'message': 'Message sent ',
            'year': datetime.now().year,
        }
    )


def cofc(request):
    """Renders the cofc page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'website/cofc.html',
        {
            'title': 'Code of Conduct',
            'message': 'Code of Conduct',
            'year': datetime.now().year,
        }
    )


def manifesto(request):
    """Renders the manifesto page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'website/manifesto.html',
        {
            'title': 'Manifesto',
            'message': 'Our Manifesto',
            'year': datetime.now().year,
        }
    )


def venue(request):
    """Renders the venue page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'website/venue.html',
        {
            'title': 'Location',
            'message': 'Location',
            'year': datetime.now().year,
        }
    )


def registration(request):
    """Renders the registration page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'website/registration.html',
        {
            'title': 'Registration',
            'message': 'Registration for PyConZim',
            'year': datetime.now().year,
        }
    )


def sprints(request):
    """Renders the sprints venue page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'website/sprints.html',
        {
            'title': 'Sprints Venue',
            'message': 'Sprints Venue',
            'year': datetime.now().year,
        }
    )


def accommodation(request):
    """Renders the accommodation page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'website/accommodation.html',
        {
            'title': 'Location',
            'message': 'Location',
            'year': datetime.now().year,
        }
    )


def pyconzim_2017(request):
    """Renders the accommodation page."""
    assert isinstance(request, HttpRequest)

    return render(
        request,
        'website/pyconzim_2017.html',
        {
            'title': 'PyCon Zimbabwe 2017',
            'message': 'PyCon Zimbabwe 2017',
            'year': datetime.now().year,
        }
    )

website/templates/website/accommodation.html
{% extends "website/base_two.html" %}

{% block content %}

<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">
        <h2>Accomodation</h2>
        <br />


        <p>There are plenty of hotels near the conference venue for international delegates. The suggested hotels are:</p>
        <ul>
            <li><a target="_blank" href="http://www.zesantc.co.zw/accommodation.php">ZESA National Training Centre</a> - <strong>
                This is the conference venue.</strong></li>
            <li><a target="_blank"  href="http://www.jamesonhotel.net/">Jameson Hotel</a></li>
            <li><a target="_blank"  href="http://www.rainbowtowershotel.com">Rainbow Towers</a></li>
            <li><a target="_blank"  href="http://www.meikles.com/">Meikles Hotel</a></li>
            <li><a target="_blank"  href="http://www.crestahotels.com/hotels/cresta-oasis/">Cresta Oasis</a></li>
            <li><a target="_blank"  href="http://www.legacyhotels.co.za/en/hotels/monomotapa">Crowne Plaza</a></li>
            <li><a target="_blank"  href="http://.brontehotel.com">Brontë The Garden Hotel</a></li>
        </ul>

</div>
    <div class="col-md-1">

    </div>
</div>

{% endblock %}

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> {{ title }} - PyConZim Conference</title>
    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}" type="text/css">

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'website/font-awesome/css/font-awesome.min.css' %}" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'website/css/magnific-popup.css' %}" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'website/css/creative.css' %}" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src='https://www.google.com/recaptcha/api.js'></script>

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">PyConZim 2018</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a class="page-scroll" href="#about">About</a></li>
                            <li><a href="{% url 'website:manifesto' %}">Manifesto</a></li>
                            <li><a href="{% url 'website:registration' %}">Registration</a></li>
                            <li><a href="{% url 'website:accommodation' %}">Accommodation</a></li>
                            <li><a href="{% url 'website:venue' %}">Conference Venue</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'schedule:schedule' %}">Schedule</a>
                    </li>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Talks <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a class="page-scroll" href="#talks">Talks</a>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'talks:submit_talk' %}">Submit Talk</a></li>
                            <li><a href="{% url 'talks:talk_list' %}">Submitted Talks</a></li>
                            {% endif %}
                        </ul>
                    <li>
                        <a href="{% url 'website:cofc' %}">CoC</a>
                    </li>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Sponsors <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <li><a class="page-scroll" href="#sponsor-us">Sponsor Us</a></li>
                        <li><a class="page-scroll" href="#our-sponsors">Our Sponsors</a></li>
                        </ul>
                    </li>
                    <li>
                      <a class="page-scroll" href="#support">Support Us</a></li>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>

                    <li>
                        <a href="{% url 'website:pyconzim_2017' %}">2017</a>
                    </li>
                    <li>
                        <a href="#">Django Summit Africa 2018</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Hello {{ user.username }}! <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'profiles:profile_home' %}">Profile</a></li>
                            <li><a href="{% url 'profiles:update' user.pk %}">Update Profile</a></li>
                            <li><a href="{% url 'profiles:login_details'  user.pk %}">Log in Details</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                        </ul>
                    </li>

                    {% else %}

                    <li class="dropdown">
                        <a href="{% url 'accounts:login' %}" class="dropdown-toggle" data-toggle="dropdown">Log in/Sign Up <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'accounts:login' %}">Log in</a></li>
                            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block content %} {% endblock %}

    <hr />
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p align="center">Copyright &copy; PyCon Zimbabwe {{ year }}</p>
            </div>
        </div>
    </footer>


    <!-- jQuery -->
    <script src="{% static 'website/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'website/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.fittext.js' %}"></script>
    <script src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'website/js/creative.js' %}"></script>

</body>

</html>

website/templates/website/base_two.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }} - PyConZim Conference</title>
    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'website/css/bootstrap.min.css' %}" type="text/css">

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'website/font-awesome/css/font-awesome.min.css' %}" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'website/css/magnific-popup.css' %}" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'website/css/creative-copy.css' %}" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src='https://www.google.com/recaptcha/api.js'></script>

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'website:home' %}#page-top">PyConZim 2018</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a href="" class="dropdown-toggle" data-toggle="dropdown">About <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a class="page-scroll" href="{% url 'website:home' %}#about">About</a></li>
                        <li><a href="{% url 'website:manifesto' %}">Manifesto</a></li>
                        <li><a href="{% url 'website:registration' %}">Registration</a></li>
                        <li><a href="{% url 'website:accommodation' %}">Accommodation</a></li>
                        <li><a href="{% url 'website:venue' %}">Conference Venue</a></li>
                    </ul>
                    </li>
                    <li>
                        <a href="{% url 'schedule:schedule' %}">Schedule</a>
                    </li>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Talks <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a class="page-scroll" href="{% url 'website:home' %}#talks">Talks</a>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'talks:submit_talk' %}">Submit Talk</a></li>
                            <li><a href="{% url 'talks:talk_list' %}">Submitted Talks</a></li>
                            {% endif %}

                        </ul>
                    <li>
                        <a href="{% url 'website:cofc' %}">CoC</a>
                    </li>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Sponsors <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        <li><a class="page-scroll" href="{% url 'website:home' %}#sponsor-us">Sponsor Us</a></li>
                        <li><a class="page-scroll" href="{% url 'website:home' %}#our-sponsors">Our Sponsors</a></li>
                        </ul>
                    </li>
                    <li>
                      <a class="page-scroll" href="{% url 'website:home' %}#support">Support Us</a></li>
                    </li>
                    <li>
                        <a class="page-scroll" href="{% url 'website:home' %}#contact">Contact</a>
                    </li>
                    <li>
                        <a href="{% url 'website:pyconzim_2017' %}">2017</a>
                    </li>
                    <li>
                        <a href="#">Django Summit Africa 2018</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown">Hello {{ user.username }}! <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'profiles:profile_home' %}">Profile</a></li>
                            <li><a href="{% url 'profiles:update' user.pk %}">Update Profile</a></li>
                            <li><a href="{% url 'profiles:login_details'  user.pk %}">Log in Details</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                        </ul>
                    </li>

                    {% else %}

                    <li class="dropdown">
                        <a href="{% url 'accounts:login' %}" class="dropdown-toggle" data-toggle="dropdown">Log in/Sign Up <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'accounts:login' %}">Log in</a></li>
                            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <header>
        <div class="header-content">
            <div class="header-content-inner" style="margin-top:60px; margin-bottom:10px">
                <img src="{% static 'website/img/pyconzim.png' %}" width="200" height="200">
                <br />
                <h3>23 - 24 AUGUST</h3>
            </div>
        </div>
    </header>

    <br />

    {% block content %} {% endblock %}

    <hr />
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p align="center">Copyright &copy; PyCon Zimbabwe {{ year }}</p>
            </div>
        </div>
    </footer>


    <!-- jQuery -->
    <script src="{% static 'website/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'website/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'website/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'website/js/jquery.fittext.js' %}"></script>
    <script src="{% static 'website/js/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'website/js/creative.js' %}"></script>

</body>

</html>

website/templates/website/contact.html
{% load crispy_forms_tags %}
<form action="{% url 'website:contact' %}" method="post">
{% crispy contact_form contact_form.helper %}
{% csrf_token %}
{{ form }}
    <div class="g-recaptcha" data-sitekey="6LdCYUMUAAAAADvkVj0Poa8uCFgkGEicMYvd3GD6"></div>
</form>

website/templates/website/manifesto.html
{% extends "website/base_two.html" %}

{% block content %}

<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">

        <h2>The Big Idea</h2>

        <p>PyConZim is aimed at:</p>
            <ul>
                <li><p>nurturing the skills of local software developers</p></li>
                <li><p>supporting and encouraging the formation of local open source development communities</p></li>
                <li><p>helping equip Zimbabwe with a skillset that will enable it to build and maintain sustainable local
                    IT infrastructures</p></li>
                <li><p>helping establish open source software as an obvious choice for African agencies and the foreign
                    donor community and to establish it as a sustainable annual event.</p></li>
            </ul>

        <br />

        <h2>Conference format</h2>

        <p>The conference is modeled around traditional <a target="_blank" href="http://pycon.org">PyCons</a> held around the world.
        The conference will include:</p>
        <ul>
            <li><p>talks</p></li>
            <li><p>workshops and tutorials</p></li>
            <li><p>code sprints</p></li>
            <li><p>the community</p></li>
        </ul>

        <br />

        <h2>Objectives</h2>

        <p>Through the conference:</p>

        <p>local people of all levels of skill, including developers, students and children:</p>

        <ul>
            <li><p>will have been introduced to new:</p>
                <ul>
                    <li><p>ideas</p></li>
                    <li><p>skills, techniques, knowledge</p></li>
                    <li><p>communities</p></li>
                </ul>
            </li>
            <li><p>will have been introduced to active participation in some of the world’s largest open source software</li>
            <li><p>will have formed communities and networks</p></li>
            <li><p>members of the international Python community will have established contact and formed connections with
                members of the local community projects</p></li>
            </ul>

    </div>
    <div class="col-md-1">

    </div>
</div>

{% endblock %}

website/templates/website/subscribe.html
{% load crispy_forms_tags %}
<form action="{% url 'website:subscribe' %}" method="post">
{% crispy subscribe_form subscribe_form.helper %}
{% csrf_token %}
{{ form }}
</form>

website/templates/website/success.html
{% extends "website/base_two.html" %}

{% block content %}

<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">

        <p align="justify"><strong><h4>Thank you for subscribing.</h4></strong>
Thank you for taking your time to subscribe for our newsletter and updates. We promise you we will not spam you and will
            only send communications regarding the conference.<br /> <br/> Good day.
</p>


    </div>
    <div class="col-md-1">

    </div>
</div>

{% endblock %}