talks/urls.py
from rest_framework import routers

from talks.views import TalkViewsSets
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from talks import views


app_name = 'talks'
router = routers.DefaultRouter()
router.register(r'talks', TalkViewsSets)


urlpatterns = [
    url(r'^submit_talk', login_required(views.submit_talk), name='submit_talk'),
    # url(r'^talk_list', login_required(views.TalkList.as_view()), name='talk_list'),
    url(r'^edit_talk/(?P<pk>\d+)/$', login_required(views.TalkView.as_view()), name='edit_talk'),
    url(r'^submitted', login_required(views.SuccessView.as_view()), name='submitted'),
    url(r'^accepted_talks', views.AcceptedTalksView.as_view(), name='accepted_talks'),
    # url(r'^talk_details/(?P<pk>\d+)/$', views.TalkDetailView.as_view(), name='talk_details'),
    ]

urlpatterns += router.urls

talks/models.py
from django.db import models
from markitup.fields import MarkupField
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.models import User


class Proposal(models.Model):
    TALK_TYPES = (
        ('Keynote', "Keynote Talk - 45 mins"),
        ('Short Talk', "Short Talk - 30 mins"),
        ('Long Talk', "Long Talk - 1 hour"),
        ('Tutorial', "Tutorial - 2 hours or more"),
    )

    STATUS = (('S', 'Submitted'),
              ('A', 'Accepted'),
              ('W', 'Waiting List'),
              ('R', 'Rejected'),)

    EXPERIENCE_LEVEL = (('Beginners', 'Beginners, no prior knowledge of Python required'),
                        ('Mid-level Programmers', 'Average, some prior knowledge of Python required'),
                        ('Senior Programmers', 'Good Python programmers level'),
                        ('Expert Programmers', 'Experienced Python programmers level'))

    # proposal = models.CharField(max_length=255, blank=False)
    title = models.CharField(max_length=1024)
    abstract = MarkupField(help_text="Describe what your talk is about")
    talk_type = models.CharField(choices=TALK_TYPES, max_length=20)
    proposal_id = models.AutoField(primary_key=True, default=None)
    notes = models.TextField(default='', help_text = "Anything else you would want the organizers to know." 
                             "Wi-fi requirments, if tutorial, number of people you can manage e.t.c."
                             "This will not be published on website.", blank=True, null=True
                             )
    user = models.ForeignKey(User, related_name="proposals", default='')
    status = models.CharField(choices=STATUS, max_length=1, default='')
    experience_level = models.CharField(choices=EXPERIENCE_LEVEL, max_length=30, default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("home")

talks/forms.py
from talks.models import Proposal
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from markitup.widgets import MarkItUpWidget


class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = ('title', 'talk_type', 'abstract', 'experience_level', 'notes',)

        widgets = {
            'abstract': MarkItUpWidget(),
          }

    def __init__(self, *args, **kwargs):
        super(ProposalForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))
        self.helper.form_class = 'form-horizontal'

talks/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpRequest
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, UpdateView, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from datetime import datetime

from rest_framework import viewsets

from .serializers import TalkSerializer
from .models import Proposal
from .forms import ProposalForm
from .mixins import EditOwnTalksMixin


@login_required
def submit_talk(request):
    assert isinstance(request, HttpRequest)

    if request.method == "POST":
        form = ProposalForm(request.POST)

        if form.is_valid():
            # process the data in form.cleaned_data as required
            obj = Proposal()  # gets new object
            obj.user_id = request.user.pk
            obj.title = form.cleaned_data['title']
            obj.abstract = form.cleaned_data['abstract']
            obj.talk_type = form.cleaned_data['talk_type']
            obj.experience_level = form.cleaned_data['experience_level']
            obj.notes = form.cleaned_data['notes']
            # finally save the object in db
            obj.save()

            return HttpResponseRedirect(reverse('talks:submitted'))

    else:
        form = ProposalForm()

        return render(
            request,
            "talks/talk_form.html",
            {
                'title': 'Submit a Talk',
                'year': datetime.now().year,
                'form': form,
            }
        )


class TalkList(TemplateView):
    template_name = "talks/talk_list.html"

    def get_context_data(self, **kwargs):
        context = super(TalkList, self).get_context_data(**kwargs)
        context['title'] = "Submitted Talks"
        context['year'] = datetime.now().year
        context['submitted_talks'] = Proposal.objects.filter(user=self.request.user.pk)
        return context


class TalkView(EditOwnTalksMixin, UpdateView):
    template_name = "talks/talk.html"
    form_class = ProposalForm
    model = Proposal
    success_url = reverse_lazy('talks:submitted')

    def get_context_data(self, **kwargs):
        context = super(TalkView, self).get_context_data(**kwargs)
        context['title'] = "Talk Details"
        context['year'] = datetime.now().year
        context['talk'] = get_object_or_404(Proposal, pk=self.kwargs['pk'])
        return context


class SuccessView(TemplateView):
    template_name = "talks/success.html"

    def get_context_data(self, **kwargs):
        context = super(SuccessView, self).get_context_data(**kwargs)
        context['title'] = 'Talk Submission Successful'
        context['year'] = datetime.now().year
        return context


class TalkViewsSets(viewsets.ReadOnlyModelViewSet):
    serializer_class = TalkSerializer
    queryset = Proposal.objects.all()


class AcceptedTalksView(TemplateView):
    template_name = "talks/accepted_talks.html"

    def get_context_data(self, **kwargs):
        context = super(AcceptedTalksView, self).get_context_data(**kwargs)
        context['title'] = "Accepted Talks"
        context['year'] = datetime.now().year
        talks_list = Proposal.objects.filter(status='A').select_related('user')

        paginator = Paginator(talks_list, 10)  # Show 10 posts per page
        page = self.request.GET.get('page')
        try:
            accepted_talks = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            accepted_talks = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            accepted_talks = paginator.page(paginator.num_pages)
        context['accepted_talks'] = accepted_talks
        return context


class TalkDetailView(TemplateView):
    template_name = "talks/talk_details.html"

    def get_context_data(self, **kwargs):
        context = super(TalkDetailView, self).get_context_data(**kwargs)
        context['title'] = "Accepted Talks"
        context['year'] = datetime.now().year
        context['talk'] = get_object_or_404(Proposal, pk=self.kwargs['pk'])
        return context

talks/templates/talks/accepted_talks.html
{% extends "website/base_two.html" %}

{% block content %}

<div class="row">
    <div class="col-md-1">
    </div>

    <div class="col-md-10">
        <h2>List of Accepted Talks for PyCon Zimbabwe 2018.</h2>
        <br />

        {% if accepted_talks %}
            <p>Attending to PyCon Zimbabwe? Here are some of the talks to look forward to at PyCon Zimbabwe:</p>
            {% for talk in accepted_talks %}
                <p><a href="{% url 'talks:talk_details' pk=talk.pk %}">{{ talk.title }}  - {{ talk.user.first_name }}
                    {{ talk.user.last_name }}</a></p>
            {% endfor %}

        <div class="pager">
            <span class="previous">
            {% if accepted_talks.has_previous %}
                <a href="?page={{ accepted_talks.previous_page_number }}">&larr; Previous</a>
            {% endif %}
            </span>
            <span class="current">
                Page {{ accepted_talks.number }} of {{ accepted_talks.paginator.num_pages }}
            </span>
            <span class="next">
            {% if accepted_talks.has_next %}
                <a href="?page={{ accepted_talks.next_page_number }}" >Next &rarr;</a>
            {% endif %}
            </span>
        </div>

        {% else %}
            <p>We haven't accepted any talks yet. We will update this page as soon as we have closed our CFP and
                accepted submitted talks.</p>
        {% endif %}
    </div>

    <div class="col-md-1">
    </div>
</div>

{% endblock %}

talks/templates/talks/success.html
{% extends "website/base_two.html" %}

{% block content %}

<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">
        <h2>Talk submission successful.</h2>
        <br />
        <p>Thank you for submitting your proposal. Our organising team will get back to you. </p>


</div>
    <div class="col-md-1">

    </div>
</div>

{% endblock %}

talks/templates/talks/talk.html
{% extends "website/base_two.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">

        <h2>Edit Talk: {{ talk.title}}</h2>
        <br />
        <form method=post>
            {% crispy form form.helper %}
            {% csrf_token %}
        </form>

    </div>
    <div class="col-md-2">

    </div>
</div>

{% endblock %}

talks/templates/talks/talk_details.html
{% extends "website/base_two.html" %}

{% block content %}

<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">

        <h2>{{ talk.title }} by {{ talk.user.first_name }} {{ talk.user.last_name }}</h2>
        <br />
        <p><strong>Talk Type:</strong> {{ talk.talk_type }}</p>
        <p><strong>Intended Audience</strong>: {{ talk.experience_level }}</p>
        <br />
        <h3>Abstract</h3>
        <p>{{ talk.abstract }}</p>
        <br />
        <hr>
        <div>
            <h3>Key</h3>
            <div class="col-md-5">
                <h4>Talk Type</h4>
                <p><strong>Keynote</strong> - Keynote Talk - 45 mins</p>
                <p><strong>Short Talk</strong> - Short Talk - 30 mins
                <p><strong>Long Talk</strong> - Long Talk - 1 hour
                <p><strong>Tutorial</strong> - Tutorial - 2 hours or more

            </div>
            <div class="col-md-5">
                <h4>Intended Audience</h4>
                <p><strong>Beginners</strong> - Beginners, no prior knowledge of Python required.</p>
                <p><strong>Mid-level Programmers</strong> - Average, some prior knowledge of Python required.</p>
                <p><strong>Senior Programmers</strong> - Sound Python knowledge required.</p>
                <p><strong>Expert Programmers</strong> - Experienced Python programmers level.</p>
            </div>
        </div>


    </div>
    <div class="col-md-1">

    </div>
</div>

{% endblock %}

talks/templates/talks/talk_form.html
{% extends 'website/base_two.html' %}

{% load crispy_forms_tags %}


{% block content %}

<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
    <form action="{% url 'talks:submit_talk' %}" method="post">
    {% crispy form form.helper %}
        {% csrf_token %}
        </form>
        </div>
    <div class="col-md-2">

    </div>
</div>

{% endblock %}

talks/templates/talks/talk_list.html
{% extends "website/base_two.html" %}

{% block content %}

<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-10">
        <h2>List of your submitted talks</h2>
        <br>
        {% if submitted_talks %}

            {% for talk in submitted_talks %}

            <p><a href="{% url 'talks:edit_talk' pk=talk.pk %}">{{ talk.title }}</a></p>

            {% endfor %}

        {% else %}

            <p>You have not submitted any talks yet.</p>

        {% endif %}

        <p><a class="btn btn-default" href="{% url 'talks:submit_talk' %}">Submit Talk! &raquo;</a></p>
        <br />

</div>
    <div class="col-md-1">

    </div>
</div>

{% endblock %}