profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import UpdateProfileView, ProfileView, UpdateLoginView, CreateProfileView, PasswordView, SuccessView


app_name = 'profiles'

urlpatterns = [
    url(r'create_profile/$', login_required(CreateProfileView.as_view()), name='create_profile'),
    url(r'update/(?P<pk>\d+)/$', login_required(UpdateProfileView.as_view()), name='update'),
    url(r'profile_home/$', login_required(ProfileView.as_view()), name='profile_home'),
    url(r'password_change/(?P<pk>\d+)/$', login_required(PasswordView.as_view()), name='password_change'),
    url(r'login_details/(?P<pk>\d+)/$', login_required(UpdateLoginView.as_view()), name='login_details'),
    url(r'profile_update/$', login_required(SuccessView.as_view()), name='profile_update'),
]

talks/urls.py
from rest_framework import routers

from talks.views import TalkViewsSets
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from talks import views


app_name = 'talks'
router = routers.DefaultRouter()
router.register(r'talks', TalkViewsSets)


urlpatterns = [
    url(r'^submit_talk', login_required(views.submit_talk), name='submit_talk'),
    # url(r'^talk_list', login_required(views.TalkList.as_view()), name='talk_list'),
    url(r'^edit_talk/(?P<pk>\d+)/$', login_required(views.TalkView.as_view()), name='edit_talk'),
    url(r'^submitted', login_required(views.SuccessView.as_view()), name='submitted'),
    url(r'^accepted_talks', views.AcceptedTalksView.as_view(), name='accepted_talks'),
    # url(r'^talk_details/(?P<pk>\d+)/$', views.TalkDetailView.as_view(), name='talk_details'),
    ]

urlpatterns += router.urls

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

from libgravatar import Gravatar


class Profile(models.Model):
    user = models.OneToOneField(User, primary_key=True, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, help_text="Tell us a bit about yourself and your work with Python", blank=False)
    location = models.CharField(max_length=30, help_text="City, Country", blank=False)
    birth_date = models.DateField(null=True, help_text="Please enter your date of birth in the format YYYY-MM-DD", blank=True)
    contact_number = models.CharField(max_length=16, help_text="Please include your country code.", blank=False, null=True)
    home_page = models.CharField(max_length=255, help_text="Your website/blog URL.", null=True, blank=True)#made this optional
    twitter_handle = models.CharField(max_length=15, blank=True, null=True) #made this optional
    github_username = models.CharField(max_length=32, blank=True, null=True) #made this optional

    def get_avatar_url(self, email):
        # email = self.user.email
         g = Gravatar(email)
         return g.get_image()

    def __str__(self):
        return u'%s' % self.user

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

from .models import Profile


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio',  'location', 'birth_date', 'contact_number', 'home_page', 'twitter_handle', 'github_username')

    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id-Crispy_UpdateForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.add_input(Submit('update', 'Update Profile'))


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id-Crispy_UserForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.add_input(Submit('update', 'Update Profile'))


class PasswordForm(PasswordChangeForm):

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id-Crispy_UserForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.Layout(
            'old_password',
            'password1',
            'password2'
        )
        self.helper.add_input(Submit('update', 'Update Profile'))

profiles/views.py
from django.shortcuts import get_object_or_404, reverse
from django.views.generic import TemplateView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from datetime import datetime

from .forms import UpdateForm, UserForm, PasswordForm
from .models import Profile
from .mixins import EditOwnProfileMixin, EditOwnLoginMixin


class ProfileView(TemplateView):
    template_name = "profiles/home.html"

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['title'] = "My Profile"
        context['year'] = datetime.now().year
        context['details'] = User.objects.filter(username=self.request.user)
        context['avatar'] = Profile.get_avatar_url(self, email=self.request.user.email)
        try:
            context['user_profile'] = Profile.objects.filter(user_id=self.request.user.pk)
        except Profile.DoesNotExist:
            context['user_profile'] = ''
        return context


class CreateProfileView(TemplateView):
    template_name = "profiles/create_profile.html"
    
    def get_context_data(self, **kwargs):
        context = super(CreateProfileView, self).get_context_data(**kwargs)
        context['title'] = 'Create Profile'
        context['form'] = UpdateForm()
        context['year'] = datetime.now().year
        return context

    def post(self, request):
        profile_form = UpdateForm(request.POST)
        if profile_form.is_valid():
            # process the data in request_form.cleaned_data as required
            obj = Profile()  # gets new object
            obj.user_id = self.request.user.pk
            obj.bio = profile_form.cleaned_data['bio']
            obj.location = profile_form.cleaned_data['location']
            obj.birth_date = profile_form.cleaned_data['birth_date']
            obj.contact_number = profile_form.cleaned_data['contact_number']
            obj.home_page = profile_form.cleaned_data['home_page']
            obj.twitter_handle = profile_form.cleaned_data['twitter_handle']
            obj.github_username = profile_form.cleaned_data['github_username']
            # finally save the object in db
            obj.save()
            return HttpResponseRedirect(reverse_lazy('profiles:profile_home'))
			
        else:
	        return HttpResponseRedirect(reverse_lazy('profiles:create_profile'))


class UpdateProfileView(EditOwnProfileMixin, UpdateView):
    form_class = UpdateForm
    model = Profile
    template_name = "profiles/update.html"
    success_url = reverse_lazy('profiles:profile_update')

    def get_context_data(self, **kwargs):
        context = super(UpdateProfileView, self).get_context_data(**kwargs)
        context['title'] = 'Update Profile'
        context['year'] = datetime.now().year
        try:
            context['profile'] = Profile.objects.filter(user_id=self.request.user.pk)
        except Profile.DoesNotExist:
            context['profile'] = ''
        return context


class UpdateLoginView(EditOwnLoginMixin, UpdateView):
    form_class = UserForm
    model = User
    template_name = "profiles/login_details.html"
    success_url = reverse_lazy('profiles:profile_update')

    def get_context_data(self, **kwargs):
        context = super(UpdateLoginView, self).get_context_data(**kwargs)
        try:
            profile = User.objects.get(pk=self.request.user.pk)
        except User.DoesNotExist:
            context['profile'] = ''

        else:
            context['profile'] = profile
        context['title'] = 'Update Login Details'
        context['year'] = datetime.now().year
        return context


class PasswordView(UpdateView):
    model = User
    form_class = PasswordForm
    template_name = "profiles/password_change.html"
    success_url = reverse_lazy('profiles:profile_update')

    def get_context_data(self, **kwargs):
        context = super(PasswordView, self).get_context_data(**kwargs)
        context['title'] = 'Change Password'
        try:
            profile = get_object_or_404(User, pk=self.request.user.pk)
        except User.DoesNotExist:
            context['profile'] = ''
            return HttpResponseRedirect('profiles:create_profile')

        else:
            context['profile'] = profile
        context['year'] = datetime.now().year
        return context


class SuccessView(TemplateView):
    template_name = "profiles/success.html"

    def get_context_data(self, **kwargs):
        context = super(SuccessView, self).get_context_data(**kwargs)
        context['title'] = 'Profile Update Successful'
        context['year'] = datetime.now().year
        return context

profiles/templates/profiles/create_profile.html
{% extends 'website/base_two.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Create your profile </h2>
<br>

<form action="{% url 'profiles:create_profile' %}" method=post>
    {% crispy form form.helper %}
          {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}

profiles/templates/profiles/home.html
{% extends 'website/base_two.html' %}

{% block content %}
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-6">

<br>
<h2>Your Profile</h2>
<br>
{% if user_profile %}

{% for detail in details %}
<h3>Personal Details</h3>
<p><strong>First Name:</strong> {{ detail.first_name }}
<br>
    <strong>Last Name:</strong> {{ detail.last_name }}
    <br>
        <strong>Email Address:</strong> {{ detail.email }}
</p>
<p><a class="btn btn-default" href="{% url 'profiles:login_details' pk=detail.id %}">Update Your Personal Details Now &raquo;</a>
<a class="btn btn-default" href="{% url 'talks:submit_talk' %}">Submit Talk! &raquo;</a>
</p>

{% endfor %}

<hr>

{% for user_p in user_profile %}
<h3>Bio Information</h3>
<p><strong>Date of Birth:</strong> {{ user_p.birth_date }}
    <br>
    <strong>Bio:</strong> {{ user_p.bio }}</p>
<hr>
<h3>Contact Details</h3>
<p>
<strong>Contact Number:</strong> {{ user_p.contact_number }}
    <br>
<strong>Location:</strong> {{ user_p.location }}
    <br>
<strong>Home page:</strong> {{ user_p.home_page }}
    <br>
<strong>Twitter Handler:</strong> {{ user_p.twitter_handle }}
    <br>
<strong>GitHub Username:</strong> {{ user_p.github_username }}
</p>


</p>
{% endfor %}


<p><a class="btn btn-default" href="{% url 'profiles:update' pk=user.id %}">Update Profile &raquo;</a>
<a class="btn btn-default" href="{% url 'talks:submit_talk' %}">Submit Talk! &raquo;</a>
</p>

{% else %}

<p>You have not created a profile yet. Please click the button below to create your profile.</p>

<br>
<p><a class="btn btn-default" href="{% url 'profiles:create_profile' %}">Create Your Profile Now &raquo;</a></p>
{% endif %}

     </div>
    <div class="col-md-4">
     <img class="team-thumb img-circle" src="{{ avatar }}" alt="">
    </div>
</div>

{% endblock %}

profiles/templates/profiles/login_details.html
{% extends 'website/base_two.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Update your login details</h2>
<br>

<form action="" method=post>
    {% crispy form form.helper %}
          {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}

profiles/templates/profiles/password_change.html
{% extends 'website/base_two.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Change your password</h2>
<br>

<form action="{% url 'profiles:password_change' user.pk %}" method=post>
    {% crispy form form.helper %}
          {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}

profiles/templates/profiles/success.html
{% extends 'website/base_two.html' %}

{% block content %}
<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
<h2> Profile Update Successful! </h2>
<br>
<p>Your changes have been updated successfully.
</p>

   </div>
    <div class="col-md-2">

    </div>
</div>

{% endblock %}

profiles/templates/profiles/update.html
{% extends 'website/base_two.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-3">

    </div>
    <div class="col-md-6">
<h2>Update your Profile </h2>
<br>

<form action="" method=post>
 {% crispy form form.helper %}
        {% csrf_token %}
</form>

      </div>
    <div class="col-md-3">

    </div>
</div>

{% endblock %}